package com.webhook.platform.worker.domain.repository;

import com.webhook.platform.worker.domain.entity.Delivery;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import org.springframework.data.jpa.repository.Modifying;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

@Repository
public interface DeliveryRepository extends JpaRepository<Delivery, UUID> {

    // Taking the claim away revokes the token too, so the abandoned attempt's late
    // finalizer cannot write to a row this sweep just released.
    @Modifying
    @Query(value = "UPDATE deliveries SET status = 'PENDING', claim_token = NULL, " +
           "next_retry_at = now(), updated_at = now(), version = version + 1 " +
           "WHERE status = 'PROCESSING' AND (last_attempt_at < :threshold OR (last_attempt_at IS NULL AND updated_at < :threshold))", nativeQuery = true)
    int resetStuckDeliveries(@Param("threshold") Instant threshold);

    /**
     * Recovers rows left PENDING with next_retry_at wiped, which neither findPendingRetryIds
     * nor resetStuckDeliveries can see. Gated on updated_at so freshly ingested deliveries —
     * also PENDING with a null next_retry_at — are never swept.
     */
    @Modifying
    @Query(value = "UPDATE deliveries SET next_retry_at = now(), updated_at = now(), version = version + 1 " +
           "WHERE status = 'PENDING' AND next_retry_at IS NULL AND updated_at < :threshold", nativeQuery = true)
    int resetStrandedPendingDeliveries(@Param("threshold") Instant threshold);


    @Query(value = """
            SELECT id FROM (
                SELECT d.id,
                       ROW_NUMBER() OVER (PARTITION BY d.endpoint_id ORDER BY d.next_retry_at ASC) AS rn_ep,
                       ROW_NUMBER() OVER (PARTITION BY e.project_id ORDER BY d.next_retry_at ASC) AS rn_proj
                FROM deliveries d
                JOIN endpoints e ON d.endpoint_id = e.id
                WHERE d.status = :#{#status.name()} AND d.next_retry_at IS NOT NULL AND d.next_retry_at <= :now
            ) sub WHERE rn_ep <= :maxPerEndpoint AND rn_proj <= :maxPerProject
            ORDER BY rn_proj ASC, rn_ep ASC LIMIT :limit
            """, nativeQuery = true)
    List<UUID> findPendingRetryIds(
            @Param("status") Delivery.DeliveryStatus status,
            @Param("now") Instant now,
            @Param("limit") int limit,
            @Param("maxPerEndpoint") int maxPerEndpoint,
            @Param("maxPerProject") int maxPerProject
    );

    @Query(value = """
            SELECT * FROM deliveries WHERE id IN :ids ORDER BY next_retry_at ASC FOR UPDATE SKIP LOCKED
            """, nativeQuery = true)
    List<Delivery> lockByIds(@Param("ids") List<UUID> ids);

    @Modifying
    @Query(value = "UPDATE deliveries SET status = 'PROCESSING', claim_token = :claimToken, " +
            "last_attempt_at = now(), updated_at = now(), version = version + 1 " +
            "WHERE id = :id AND status = 'PENDING'", nativeQuery = true)
    int claimForProcessing(@Param("id") UUID id, @Param("claimToken") UUID claimToken);

    // Generated by the caller, not gen_random_uuid(): claimForProcessing above has no result
    // set the winner could read the token back from.
    @Query(value = "UPDATE deliveries SET status = 'PROCESSING', claim_token = :claimToken, " +
            "last_attempt_at = now(), updated_at = now(), version = version + 1 " +
            "WHERE id = :id AND status = 'PENDING' " +
            "RETURNING *", nativeQuery = true)
    Delivery claimForProcessingAndReturn(@Param("id") UUID id, @Param("claimToken") UUID claimToken);

    /**
     * CAS claim for the retry path.
     *
     * <p>Swaps the token the scheduler published with for a fresh one, but only while the row
     * still carries it. Two things correctly claim nothing: a redelivered Kafka message, and a
     * send the scheduler gave up waiting on that lands anyway after the row was re-claimed.
     *
     * <p>The Delivery comes back so the winner needs no second read, and so a claim that applied
     * to nothing is distinguishable from a missing row.
     */
    @Query(value = "UPDATE deliveries SET claim_token = :newClaimToken, " +
            "updated_at = now(), version = version + 1 " +
            "WHERE id = :id AND status = 'PROCESSING' AND claim_token = :expectedClaimToken " +
            "RETURNING *", nativeQuery = true)
    Delivery claimRetryForProcessing(@Param("id") UUID id,
            @Param("expectedClaimToken") UUID expectedClaimToken,
            @Param("newClaimToken") UUID newClaimToken);

    @Modifying
    @Query(value = "UPDATE deliveries SET attempt_count = attempt_count + 1, " +
            "updated_at = now(), version = version + 1 " +
            "WHERE id = :id", nativeQuery = true)
    int incrementAttemptCount(@Param("id") UUID id);

    /**
     * Decides only whether anything is still outstanding in the gap; the timeout itself is
     * measured from when the blocked successor was first buffered. Null when nothing is.
     */
    @Query("SELECT MIN(d.createdAt) FROM Delivery d WHERE d.endpointId = :endpointId " +
            "AND d.sequenceNumber BETWEEN :rangeStart AND :rangeEnd AND d.status IN ('PENDING', 'PROCESSING')")
    Instant findOldestPendingCreatedAt(
            @Param("endpointId") UUID endpointId,
            @Param("rangeStart") long rangeStart,
            @Param("rangeEnd") long rangeEnd
    );

    @Query("SELECT COUNT(d) FROM Delivery d WHERE d.status = 'PENDING' AND d.createdAt > :since")
    long countPending(@Param("since") Instant since);

    @Query("SELECT COUNT(d) FROM Delivery d WHERE d.status = 'PROCESSING' AND d.createdAt > :since")
    long countProcessing(@Param("since") Instant since);

    @Query("SELECT COUNT(d) FROM Delivery d WHERE d.status = 'DLQ' AND d.createdAt > :since")
    long countDlq(@Param("since") Instant since);

    /** The actionable DLQ backlog: rows not yet retried or purged. */
    @Query("SELECT COUNT(d) FROM Delivery d WHERE d.status = 'DLQ'")
    long countDlqTotal();

    @Query("SELECT MIN(d.createdAt) FROM Delivery d WHERE d.status = 'PENDING'")
    Instant findOldestPendingCreatedAtGlobal();

    /**
     * Finds IDs of deliveries that have been in PENDING status since before the given cutoff.
     * Used by StaleDeliveryEscalationService to hard-cap escalate stale deliveries to DLQ.
     */
    @Query(value = """
            SELECT d.id FROM deliveries d
            WHERE d.status = 'PENDING' AND d.created_at < :cutoff
            ORDER BY d.created_at ASC
            LIMIT :limit
            FOR UPDATE SKIP LOCKED
            """, nativeQuery = true)
    List<UUID> findStaleDeliveryIds(@Param("cutoff") Instant cutoff, @Param("limit") int limit);
}
