package com.webhook.platform.worker.domain.repository;

import com.webhook.platform.worker.domain.entity.Delivery;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import org.springframework.data.jpa.repository.Modifying;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

@Repository
public interface DeliveryRepository extends JpaRepository<Delivery, UUID> {

    // claim_token = NULL: taking the claim away must also revoke it, so the abandoned
    // attempt's own late finalizer no longer matches and cannot write to a row this
    // sweep has just released back to the retry ladder.
    @Modifying
    @Query(value = "UPDATE deliveries SET status = 'PENDING', claim_token = NULL, " +
           "next_retry_at = now(), updated_at = now(), version = version + 1 " +
           "WHERE status = 'PROCESSING' AND (last_attempt_at < :threshold OR (last_attempt_at IS NULL AND updated_at < :threshold))", nativeQuery = true)
    int resetStuckDeliveries(@Param("threshold") Instant threshold);

    /**
     * Belt-and-braces recovery for rows stuck PENDING with next_retry_at wiped but never
     * transitioned to PROCESSING (e.g. legacy rows claimed under the pre-fix scheduler
     * contract). Such rows are invisible to both findPendingRetryIds (needs a non-null
     * next_retry_at) and resetStuckDeliveries (needs status = PROCESSING). Gated on
     * updated_at so freshly ingested deliveries — also PENDING with next_retry_at NULL,
     * relying on their single outbox Kafka message — are never swept.
     */
    @Modifying
    @Query(value = "UPDATE deliveries SET next_retry_at = now(), updated_at = now(), version = version + 1 " +
           "WHERE status = 'PENDING' AND next_retry_at IS NULL AND updated_at < :threshold", nativeQuery = true)
    int resetStrandedPendingDeliveries(@Param("threshold") Instant threshold);


    @Query(value = """
            SELECT id FROM (
                SELECT d.id,
                       ROW_NUMBER() OVER (PARTITION BY d.endpoint_id ORDER BY d.next_retry_at ASC) AS rn_ep,
                       ROW_NUMBER() OVER (PARTITION BY e.project_id ORDER BY d.next_retry_at ASC) AS rn_proj
                FROM deliveries d
                JOIN endpoints e ON d.endpoint_id = e.id
                WHERE d.status = :#{#status.name()} AND d.next_retry_at IS NOT NULL AND d.next_retry_at <= :now
            ) sub WHERE rn_ep <= :maxPerEndpoint AND rn_proj <= :maxPerProject
            ORDER BY rn_proj ASC, rn_ep ASC LIMIT :limit
            """, nativeQuery = true)
    List<UUID> findPendingRetryIds(
            @Param("status") Delivery.DeliveryStatus status,
            @Param("now") Instant now,
            @Param("limit") int limit,
            @Param("maxPerEndpoint") int maxPerEndpoint,
            @Param("maxPerProject") int maxPerProject
    );

    @Query(value = """
            SELECT * FROM deliveries WHERE id IN :ids ORDER BY next_retry_at ASC FOR UPDATE SKIP LOCKED
            """, nativeQuery = true)
    List<Delivery> lockByIds(@Param("ids") List<UUID> ids);

    @Modifying
    @Query(value = "UPDATE deliveries SET status = 'PROCESSING', claim_token = :claimToken, " +
            "last_attempt_at = now(), updated_at = now(), version = version + 1 " +
            "WHERE id = :id AND status = 'PENDING'", nativeQuery = true)
    int claimForProcessing(@Param("id") UUID id, @Param("claimToken") UUID claimToken);

    // The token is generated by the caller rather than with gen_random_uuid() so the
    // value is known to the attempt that just won the claim — RETURNING * hands it back
    // here, but claimForProcessing above has no result set to read it from.
    @Query(value = "UPDATE deliveries SET status = 'PROCESSING', claim_token = :claimToken, " +
            "last_attempt_at = now(), updated_at = now(), version = version + 1 " +
            "WHERE id = :id AND status = 'PENDING' " +
            "RETURNING *", nativeQuery = true)
    Delivery claimForProcessingAndReturn(@Param("id") UUID id, @Param("claimToken") UUID claimToken);

    /**
     * CAS claim for the retry path.
     *
     * <p>RetrySchedulerService has already moved the row PENDING -&gt; PROCESSING under a
     * fencing token and published that token with the Kafka message. This swaps it for a
     * fresh one, but only if the row still carries the token the message was published with.
     * Two things lose that race and correctly claim nothing:</p>
     *
     * <ul>
     *   <li>a second delivery of the same Kafka message — at-least-once means a rebalance
     *       that loses an offset commit replays it, and both copies used to read PROCESSING
     *       and double-POST;</li>
     *   <li>a message whose send the scheduler gave up waiting on. On "Send confirmation
     *       timeout" it hands the row back as PENDING with a null token, the next poll
     *       re-claims it under a new token and publishes again — and the original send often
     *       lands anyway. That late message carries the old token, so it now stops here
     *       instead of dispatching alongside the fresh one.</li>
     * </ul>
     *
     * <p>The Delivery is returned so the winner has the row it just claimed without a second
     * read, and so a claim that applied to nothing is distinguishable from a missing row.</p>
     */
    @Query(value = "UPDATE deliveries SET claim_token = :newClaimToken, " +
            "updated_at = now(), version = version + 1 " +
            "WHERE id = :id AND status = 'PROCESSING' AND claim_token = :expectedClaimToken " +
            "RETURNING *", nativeQuery = true)
    Delivery claimRetryForProcessing(@Param("id") UUID id,
            @Param("expectedClaimToken") UUID expectedClaimToken,
            @Param("newClaimToken") UUID newClaimToken);

    @Modifying
    @Query(value = "UPDATE deliveries SET attempt_count = attempt_count + 1, " +
            "updated_at = now(), version = version + 1 " +
            "WHERE id = :id", nativeQuery = true)
    int incrementAttemptCount(@Param("id") UUID id);

    /**
     * Finds the oldest createdAt among deliveries still PENDING/PROCESSING for this endpoint
     * whose sequence number falls in the missing range {@code [rangeStart, rangeEnd]}
     * (inclusive). Used only to decide whether *anything* is still outstanding in the gap —
     * the actual timeout decision is driven by when the blocked successor was first buffered
     * (see {@code OrderingBufferService#isGapTimedOut}), not by this timestamp. An empty range
     * (rangeStart &gt; rangeEnd) or a range with nothing pending both return null.
     */
    @Query("SELECT MIN(d.createdAt) FROM Delivery d WHERE d.endpointId = :endpointId " +
            "AND d.sequenceNumber BETWEEN :rangeStart AND :rangeEnd AND d.status IN ('PENDING', 'PROCESSING')")
    Instant findOldestPendingCreatedAt(
            @Param("endpointId") UUID endpointId,
            @Param("rangeStart") long rangeStart,
            @Param("rangeEnd") long rangeEnd
    );

    @Query("SELECT COUNT(d) FROM Delivery d WHERE d.status = 'PENDING' AND d.createdAt > :since")
    long countPending(@Param("since") Instant since);

    @Query("SELECT COUNT(d) FROM Delivery d WHERE d.status = 'PROCESSING' AND d.createdAt > :since")
    long countProcessing(@Param("since") Instant since);

    @Query("SELECT COUNT(d) FROM Delivery d WHERE d.status = 'DLQ' AND d.createdAt > :since")
    long countDlq(@Param("since") Instant since);

    /**
     * All-time count of deliveries still sitting in {@code DeliveryStatus.DLQ} -- i.e. the
     * actionable backlog: deliveries that have not yet been retried (back to PENDING) or
     * purged via {@code DlqService}. Used by {@code DlqMonitoringService} as the
     * source of truth for the "needs manual intervention" gauge, in place of a Kafka
     * latest-earliest offset computation that could only ever measure topic retention, not
     * whether anything had actually been remediated.
     */
    @Query("SELECT COUNT(d) FROM Delivery d WHERE d.status = 'DLQ'")
    long countDlqTotal();

    /**
     * Finds the oldest pending delivery's createdAt timestamp (globally).
     * Used by StaleDeliveryEscalationService to compute the oldest pending age metric.
     */
    @Query("SELECT MIN(d.createdAt) FROM Delivery d WHERE d.status = 'PENDING'")
    Instant findOldestPendingCreatedAtGlobal();

    /**
     * Finds IDs of deliveries that have been in PENDING status since before the given cutoff.
     * Used by StaleDeliveryEscalationService to hard-cap escalate stale deliveries to DLQ.
     */
    @Query(value = """
            SELECT d.id FROM deliveries d
            WHERE d.status = 'PENDING' AND d.created_at < :cutoff
            ORDER BY d.created_at ASC
            LIMIT :limit
            FOR UPDATE SKIP LOCKED
            """, nativeQuery = true)
    List<UUID> findStaleDeliveryIds(@Param("cutoff") Instant cutoff, @Param("limit") int limit);
}
