package com.webhook.platform.worker.domain.repository;

import com.webhook.platform.common.enums.ForwardAttemptStatus;
import com.webhook.platform.worker.domain.entity.IncomingForwardAttempt;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

@Repository
public interface IncomingForwardAttemptRepository extends JpaRepository<IncomingForwardAttempt, UUID> {

        List<IncomingForwardAttempt> findByIncomingEventIdAndDestinationIdOrderByAttemptNumberDesc(
                        UUID incomingEventId, UUID destinationId);

        @Query(value = """
                        SELECT id FROM (
                            SELECT id, ROW_NUMBER() OVER (PARTITION BY destination_id ORDER BY next_retry_at ASC) AS rn
                            FROM incoming_forward_attempts
                            WHERE status = :#{#status.name()} AND next_retry_at IS NOT NULL AND next_retry_at <= :now
                        ) sub WHERE rn <= :maxPerDest ORDER BY rn ASC LIMIT :limit
                        """, nativeQuery = true)
        List<UUID> findPendingRetryIds(@Param("status") ForwardAttemptStatus status,
                        @Param("now") Instant now,
                        @Param("limit") int limit,
                        @Param("maxPerDest") int maxPerDest);

        @Query(value = "SELECT * FROM incoming_forward_attempts WHERE id IN :ids ORDER BY next_retry_at ASC FOR UPDATE SKIP LOCKED",
                        nativeQuery = true)
        List<IncomingForwardAttempt> lockByIds(@Param("ids") List<UUID> ids);

        @Query("SELECT COALESCE(MAX(a.attemptNumber), 0) FROM IncomingForwardAttempt a " +
                        "WHERE a.incomingEventId = :eventId AND a.destinationId = :destinationId")
        int findMaxAttemptNumber(@Param("eventId") UUID eventId, @Param("destinationId") UUID destinationId);

        /** Token generated by the caller, so the winner knows what it must still match. */
        @Modifying
        @Query(value = "UPDATE incoming_forward_attempts SET status = 'PROCESSING', " +
                        "started_at = now(), claim_token = :claimToken " +
                        "WHERE incoming_event_id = :eventId AND destination_id = :destinationId " +
                        "AND attempt_number = :attemptNumber AND status = 'PENDING'", nativeQuery = true)
        int claimForProcessing(@Param("eventId") UUID eventId,
                        @Param("destinationId") UUID destinationId,
                        @Param("attemptNumber") int attemptNumber,
                        @Param("claimToken") UUID claimToken);

        @Modifying
        // Cleared alongside the status: a swept attempt must not still match its own token.
        @Query(value = "UPDATE incoming_forward_attempts SET status = 'PENDING', " +
                        "next_retry_at = now(), claim_token = NULL " +
                        "WHERE status = 'PROCESSING' AND started_at < :threshold", nativeQuery = true)
        int resetStuckForwardAttempts(@Param("threshold") Instant threshold);

        /**
         * CAS claim for the retry path: bumps the token the scheduler stamped, but only while
         * it still matches, so a redelivered Kafka message updates no rows.
         */
        @Modifying
        @Query(value = "UPDATE incoming_forward_attempts SET started_at = now(), " +
                        "claim_token = :claimToken " +
                        "WHERE incoming_event_id = :eventId AND destination_id = :destinationId " +
                        "AND attempt_number = :attemptNumber AND status = 'PROCESSING' " +
                        "AND started_at = :expectedStartedAt", nativeQuery = true)
        int claimRetryForProcessing(@Param("eventId") UUID eventId,
                        @Param("destinationId") UUID destinationId,
                        @Param("attemptNumber") int attemptNumber,
                        @Param("expectedStartedAt") Instant expectedStartedAt,
                        @Param("claimToken") UUID claimToken);

        /**
         * Age of the longest-outstanding Forward, measured from when the webhook arrived — not
         * from the attempt row, which Incoming re-creates per Attempt.
         */
        @Query(value = """
                        SELECT MIN(e.received_at) FROM incoming_forward_attempts a
                        JOIN incoming_events e ON e.id = a.incoming_event_id
                        WHERE a.status = 'PENDING'
                        """, nativeQuery = true)
        Instant findOldestPendingReceivedAt();

        /**
         * PENDING Attempts whose Incoming Event arrived before the cutoff, oldest first.
         *
         * <p>{@code FOR UPDATE OF a SKIP LOCKED} because the caller publishes a DLQ
         * notification per row: without it two worker replicas would select the same rows and
         * each emit a duplicate notification for the same Forward.
         */
        @Query(value = """
                        SELECT a.id FROM incoming_forward_attempts a
                        JOIN incoming_events e ON e.id = a.incoming_event_id
                        WHERE a.status = 'PENDING' AND e.received_at < :cutoff
                        ORDER BY e.received_at ASC
                        LIMIT :limit
                        FOR UPDATE OF a SKIP LOCKED
                        """, nativeQuery = true)
        List<UUID> findStaleForwardAttemptIds(@Param("cutoff") Instant cutoff, @Param("limit") int limit);

        @Query("SELECT COUNT(a) FROM IncomingForwardAttempt a WHERE a.status = 'PENDING' AND a.createdAt > :since")
        long countPending(@Param("since") Instant since);

        @Query("SELECT COUNT(a) FROM IncomingForwardAttempt a WHERE a.status = 'PROCESSING' AND a.createdAt > :since")
        long countProcessing(@Param("since") Instant since);

        @Query("SELECT COUNT(a) FROM IncomingForwardAttempt a WHERE a.status = 'DLQ' AND a.createdAt > :since")
        long countDlq(@Param("since") Instant since);

        /**
         * The actionable Incoming DLQ backlog. Not windowed, unlike {@link #countDlq(Instant)}:
         * a Forward abandoned a week ago still needs a human to decide about it.
         */
        @Query("SELECT COUNT(a) FROM IncomingForwardAttempt a WHERE a.status = 'DLQ'")
        long countDlqTotal();
}
