apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hookflow.fullname" . }}-config
  labels:
    {{- include "hookflow.labels" . | nindent 4 }}
data:
  DB_HOST: {{ include "hookflow.database.host" . | quote }}
  DB_PORT: {{ include "hookflow.database.port" . | quote }}
  DB_NAME: {{ .Values.postgresql.auth.database | default .Values.postgresql.external.database | quote }}
  DB_USER: {{ .Values.postgresql.auth.username | default .Values.postgresql.external.username | quote }}
  
  KAFKA_BOOTSTRAP_SERVERS: {{ include "hookflow.kafka.bootstrapServers" . | quote }}
  
  REDIS_HOST: {{ include "hookflow.redis.host" . | quote }}
  REDIS_PORT: {{ include "hookflow.redis.port" . | quote }}
