-- ============================================================
-- Production billing schema: subscriptions, events, invoices,
-- payments, scheduled plan changes
-- ============================================================

-- 1. Billing subscriptions — one active per organization
CREATE TABLE billing_subscriptions (
    id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id             UUID         NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    plan_id                     UUID         NOT NULL REFERENCES plans(id),
    provider_code               VARCHAR(50)  NOT NULL,  -- stripe, wayforpay, manual, noop
    status                      VARCHAR(30)  NOT NULL DEFAULT 'ACTIVE',
    -- Provider-specific external IDs
    external_subscription_id    VARCHAR(255),
    external_customer_id        VARCHAR(255),
    -- Billing cycle
    current_period_start        TIMESTAMPTZ,
    current_period_end          TIMESTAMPTZ,
    -- Cancellation
    cancel_at_period_end        BOOLEAN      NOT NULL DEFAULT false,
    cancelled_at                TIMESTAMPTZ,
    -- Trial
    trial_start                 TIMESTAMPTZ,
    trial_end                   TIMESTAMPTZ,
    -- Recurring token (WayForPay recToken, etc.)
    recurring_token_encrypted   TEXT,
    -- Payment method snapshot
    card_last4                  VARCHAR(4),
    card_brand                  VARCHAR(20),
    -- Currency
    currency                    VARCHAR(3)   NOT NULL DEFAULT 'USD',
    -- Meta
    metadata                    JSONB        DEFAULT '{}',
    created_at                  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_billing_subs_org ON billing_subscriptions(organization_id);
CREATE INDEX idx_billing_subs_active ON billing_subscriptions(status)
    WHERE status IN ('ACTIVE', 'PAST_DUE', 'TRIALING', 'GRACE_PERIOD');
CREATE INDEX idx_billing_subs_external_sub ON billing_subscriptions(external_subscription_id)
    WHERE external_subscription_id IS NOT NULL;
CREATE INDEX idx_billing_subs_external_cust ON billing_subscriptions(external_customer_id)
    WHERE external_customer_id IS NOT NULL;
CREATE INDEX idx_billing_subs_period_end ON billing_subscriptions(current_period_end)
    WHERE status = 'ACTIVE';
CREATE INDEX idx_billing_subs_provider ON billing_subscriptions(provider_code, status);

-- 2. Subscription event log — audit trail of every state change
CREATE TABLE billing_subscription_events (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    subscription_id   UUID         NOT NULL REFERENCES billing_subscriptions(id) ON DELETE CASCADE,
    event_type        VARCHAR(50)  NOT NULL,  -- CREATED, ACTIVATED, RENEWED, PAYMENT_SUCCEEDED, PAYMENT_FAILED, PAST_DUE, GRACE_PERIOD_STARTED, SUSPENDED, CANCELLED, PLAN_CHANGED, TRIAL_STARTED, TRIAL_ENDED, RESUMED
    from_status       VARCHAR(30),
    to_status         VARCHAR(30),
    from_plan_id      UUID         REFERENCES plans(id),
    to_plan_id        UUID         REFERENCES plans(id),
    reason            TEXT,
    metadata          JSONB        DEFAULT '{}',
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_billing_sub_events_sub ON billing_subscription_events(subscription_id, created_at DESC);
CREATE INDEX idx_billing_sub_events_type ON billing_subscription_events(event_type, created_at DESC);

-- 3. Invoices — local records (synced from provider or generated by our scheduler)
CREATE TABLE billing_invoices (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id         UUID         NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    subscription_id         UUID         REFERENCES billing_subscriptions(id) ON DELETE SET NULL,
    provider_code           VARCHAR(50)  NOT NULL,
    external_invoice_id     VARCHAR(255),
    invoice_number          VARCHAR(100),
    status                  VARCHAR(30)  NOT NULL DEFAULT 'DRAFT',  -- DRAFT, OPEN, PAID, PAST_DUE, VOID, UNCOLLECTIBLE
    -- Amounts (in smallest currency unit — cents, kopecks)
    subtotal_cents          BIGINT       NOT NULL DEFAULT 0,
    tax_cents               BIGINT       NOT NULL DEFAULT 0,
    total_cents             BIGINT       NOT NULL DEFAULT 0,
    currency                VARCHAR(3)   NOT NULL DEFAULT 'USD',
    -- Period this invoice covers
    period_start            TIMESTAMPTZ,
    period_end              TIMESTAMPTZ,
    -- Dates
    due_date                TIMESTAMPTZ,
    paid_at                 TIMESTAMPTZ,
    voided_at               TIMESTAMPTZ,
    -- URLs from provider
    hosted_url              VARCHAR(2048),
    pdf_url                 VARCHAR(2048),
    -- Detailed breakdown
    line_items              JSONB        DEFAULT '[]',
    metadata                JSONB        DEFAULT '{}',
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_billing_invoices_org ON billing_invoices(organization_id, created_at DESC);
CREATE INDEX idx_billing_invoices_sub ON billing_invoices(subscription_id) WHERE subscription_id IS NOT NULL;
CREATE INDEX idx_billing_invoices_status ON billing_invoices(status) WHERE status IN ('OPEN', 'PAST_DUE');
CREATE INDEX idx_billing_invoices_external ON billing_invoices(external_invoice_id) WHERE external_invoice_id IS NOT NULL;
CREATE INDEX idx_billing_invoices_due ON billing_invoices(due_date) WHERE status = 'OPEN';

-- 4. Payments — individual payment attempts (multiple attempts per invoice possible)
CREATE TABLE billing_payments (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_id              UUID         REFERENCES billing_invoices(id) ON DELETE SET NULL,
    organization_id         UUID         NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    subscription_id         UUID         REFERENCES billing_subscriptions(id) ON DELETE SET NULL,
    provider_code           VARCHAR(50)  NOT NULL,
    external_payment_id     VARCHAR(255),
    status                  VARCHAR(30)  NOT NULL DEFAULT 'PENDING',  -- PENDING, PROCESSING, SUCCEEDED, FAILED, REFUNDED, PARTIALLY_REFUNDED
    -- Amounts
    amount_cents            BIGINT       NOT NULL,
    currency                VARCHAR(3)   NOT NULL DEFAULT 'USD',
    refunded_cents          BIGINT       NOT NULL DEFAULT 0,
    -- Payment method info
    payment_method          VARCHAR(50),   -- card, bank_transfer, privat24, google_pay, apple_pay
    card_last4              VARCHAR(4),
    card_brand              VARCHAR(20),   -- visa, mastercard, etc.
    -- Failure info
    failure_code            VARCHAR(100),
    failure_message         TEXT,
    -- Provider response
    provider_response       JSONB        DEFAULT '{}',
    metadata                JSONB        DEFAULT '{}',
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_billing_payments_org ON billing_payments(organization_id, created_at DESC);
CREATE INDEX idx_billing_payments_invoice ON billing_payments(invoice_id) WHERE invoice_id IS NOT NULL;
CREATE INDEX idx_billing_payments_sub ON billing_payments(subscription_id) WHERE subscription_id IS NOT NULL;
CREATE INDEX idx_billing_payments_external ON billing_payments(external_payment_id) WHERE external_payment_id IS NOT NULL;
CREATE INDEX idx_billing_payments_status ON billing_payments(status, created_at DESC);

-- 5. Scheduled plan changes — upgrade/downgrade at end of billing period
CREATE TABLE billing_scheduled_changes (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id   UUID         NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    subscription_id   UUID         NOT NULL REFERENCES billing_subscriptions(id) ON DELETE CASCADE,
    from_plan_id      UUID         NOT NULL REFERENCES plans(id),
    to_plan_id        UUID         NOT NULL REFERENCES plans(id),
    change_type       VARCHAR(30)  NOT NULL DEFAULT 'PLAN_CHANGE',  -- PLAN_CHANGE, CANCELLATION
    effective_at      TIMESTAMPTZ  NOT NULL,
    status            VARCHAR(30)  NOT NULL DEFAULT 'PENDING',  -- PENDING, APPLIED, CANCELLED
    applied_at        TIMESTAMPTZ,
    cancelled_at      TIMESTAMPTZ,
    reason            TEXT,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_billing_scheduled_pending ON billing_scheduled_changes(effective_at)
    WHERE status = 'PENDING';
CREATE INDEX idx_billing_scheduled_org ON billing_scheduled_changes(organization_id);
CREATE INDEX idx_billing_scheduled_sub ON billing_scheduled_changes(subscription_id);

-- 6. Cleanup: remove external_customer_id from organizations (moved to billing_subscriptions)
ALTER TABLE organizations DROP COLUMN IF EXISTS external_customer_id;
